package com.oracle.ouaf.spl.xaixapp.xaiserver.cmgenidvald;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CmGenIdVald version 3: Generic Id value Validation
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CmGenIdValdService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGenIdVald", wsdlLocation = "https://144.22.109.36:6502/ouaf/XAIApp/xaiserver/CmGenIdVald?wsdl")
public class CmGenIdValdService
        extends Service {

    private final static URL CMGENIDVALDSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGENIDVALDSERVICE_EXCEPTION;
    private final static QName CMGENIDVALDSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGenIdVald", "CmGenIdValdService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://144.22.109.36:6502/ouaf/XAIApp/xaiserver/CmGenIdVald?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGENIDVALDSERVICE_WSDL_LOCATION = url;
        CMGENIDVALDSERVICE_EXCEPTION = e;
    }

    public CmGenIdValdService() {
        super(__getWsdlLocation(), CMGENIDVALDSERVICE_QNAME);
    }

    public CmGenIdValdService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGENIDVALDSERVICE_QNAME, features);
    }

    public CmGenIdValdService(URL wsdlLocation) {
        super(wsdlLocation, CMGENIDVALDSERVICE_QNAME);
    }

    public CmGenIdValdService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGENIDVALDSERVICE_QNAME, features);
    }

    public CmGenIdValdService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmGenIdValdService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGENIDVALDSERVICE_EXCEPTION != null) {
            throw CMGENIDVALDSERVICE_EXCEPTION;
        }
        return CMGENIDVALDSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CmGenIdValdPortType
     */
    @WebEndpoint(name = "CmGenIdValdPort")
    public CmGenIdValdPortType getCmGenIdValdPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGenIdVald", "CmGenIdValdPort"), CmGenIdValdPortType.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CmGenIdValdPortType
     */
    @WebEndpoint(name = "CmGenIdValdPort")
    public CmGenIdValdPortType getCmGenIdValdPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmGenIdVald", "CmGenIdValdPort"), CmGenIdValdPortType.class, features);
    }

}
